import {
  AntiAgingSerum,
  CreamAfterSun,
  EnzymePowder,
  FacialTonic,
  FoundationBlazy1,
  HydrophilicOil,
  LipOil1,
  LipOil4,
  LipScrub,
  LipStick4,
  Mascara1,
  MaskAcids,
  MattifyingTonic,
  MoisturizingCream,
  MoisturizingMask,
  MoisturizingSerum,
  NightSerum,
  PerfectSerum,
  Powder2,
  SprayTanning,
  Sunscream,
} from "../../assets/images/images";

export const wishList = [
  {
    id: 1,
    image: LipOil1,
    title: "MIXIT Make up Glazed oil gloss, shade pale pink, 5 мл",
    price: 16.5,
    isFavorite: false,
    isBasket: false,
  },
  {
    id: 2,
    image: LipOil4,
    title: "MIXIT Make up Lip Gloss Blossy Lips, 06, 5 ml",
    price: 17.5,
    isFavorite: false,
    isBasket: false,
  },
  {
    id: 3,
    image: Mascara1,
    title: "MIXIT Make Up Glam Doll Lash Mascara Make Up, 10 g",
    price: 18.5,
    isFavorite: false,
    isBasket: false,
  },
  {
    id: 4,
    image: Powder2,
    title: "MIXIT Make Up Compact Powder color 02, 10г",
    price: 19.5,
    isFavorite: false,
    isBasket: false,
  },
  {
    id: 5,
    image: FoundationBlazy1,
    title: "MIXIT Make Up Foundation Blazy Look, 01, 30 мл",
    price: 19.5,
    isFavorite: false,
    isBasket: false,
  },
  {
    id: 6,
    image: LipStick4,
    title: "MIXIT Make Up Lipstick Balm-Look, 07, 3 г",
    price: 19.5,
    isFavorite: false,
    isBasket: false,
  },
];

export const data = [
  {
    id: "e1",
    subTitle: "Face care",
    products: [
      {
        id: 1,
        image: AntiAgingSerum,
        title: "Face-care Copper Peptides 1% + HA Serum, 30 ml",
        price: 19.5,
        isFavorite: false,
        isBasket: false,
      },
      {
        id: 2,
        image: MoisturizingSerum,
        title: "SKIN CHEMISTRY Hyaluronic Acid 1,5% Serum, 30 ml",
        price: 19.5,
        isFavorite: false,
        isBasket: false,
      },
      {
        id: 3,
        image: PerfectSerum,
        title: "Face-care SKIN CHEMISTRY Cinderella Serum, 30 ml",
        price: 19.5,
        isFavorite: false,
        isBasket: false,
      },
      {
        id: 4,
        image: NightSerum,
        title: "Face-care Skin Chemistry Retinol Power , 30 ml",
        price: 19.5,
        isFavorite: false,
        isBasket: false,
      },
    ],
  },
  {
    id: "e2",
    subTitle: "Body care",
    products: [
      {
        id: 5,
        image: EnzymePowder,
        title: "Body-care Skin Chemistry Retinol Power , 30 ml",
        price: 20,
        isFavorite: false,
        isBasket: false,
      },
      {
        id: 6,
        image: LipScrub,
        title: "MIXIT LAB Cleansing Milk, 250 мл",
        price: 18.5,
        isFavorite: false,
        isBasket: false,
      },
      {
        id: 7,
        image: MattifyingTonic,
        title: "Body-care MIXIT LAB AQUA Hyaluron Fluid, 150 мл",
        price: 17.5,
        isFavorite: false,
        isBasket: false,
      },
      {
        id: 8,
        image: SprayTanning,
        title: "Body-care Skin Chemistry Retinol Power , 30 ml",
        price: 19.5,
        isFavorite: false,
        isBasket: false,
      },
    ],
  },
  {
    id: "e3",
    subTitle: "Hair care",
    products: [
      {
        id: 9,
        image: CreamAfterSun,
        title: "AHA! Revolution Soft Peeling glycolic 5%, 100 ml",
        price: 21.5,
        isFavorite: false,
        isBasket: false,
      },
      {
        id: 10,
        image: HydrophilicOil,
        title: "MIXIT LAB AQUA Hyaluron Fluid, 50 ml",
        price: 19.5,
        isFavorite: false,
        isBasket: false,
      },
      {
        id: 11,
        image: MaskAcids,
        title: "Face-care Skin Chemistry Retinol Power , 30 ml",
        price: 15.5,
        isFavorite: false,
        isBasket: false,
      },
      {
        id: 12,
        image: FacialTonic,
        title: "AHA! Revolution Soft Peeling glycolic 5%, 100 ml",
        price: 18.5,
        isFavorite: false,
        isBasket: false,
      },
    ],
  },
  {
    id: "e4",
    subTitle: "Hand care",
    products: [
      {
        id: 13,
        image: Sunscream,
        title: "Hand-care Skin Chemistry Retinol Power , 30 ml",
        price: 18.5,
        isFavorite: false,
        isBasket: false,
      },
      {
        id: 14,
        image: MoisturizingMask,
        title: "Hand-care Detox Time Mask Puzzle 1, 60 ml",
        price: 19.5,
        isFavorite: false,
        isBasket: false,
      },
      {
        id: 15,
        image: MoisturizingCream,
        title: "Hand-care AquaLand Mask Puzzle 2, 60 ml",
        price: 20.5,
        isFavorite: false,
        isBasket: false,
      },
      {
        id: 16,
        image: MaskAcids,
        title: "Vitamin Smoothie Mask Puzzle 3, 60 ml",
        price: 17.5,
        isFavorite: false,
        isBasket: false,
      },
    ],
  },
  {
    id: "e5",
    subTitle: "Other",
    products: [
      {
        id: 17,
        image: LipOil1,
        title: "Make up Glazed oil gloss, shade pale pink, 5 мл",
        price: 16.5,
        isFavorite: false,
        isBasket: false,
      },
      {
        id: 18,
        image: LipOil4,
        title: "Make up Lip Gloss Blossy Lips, 06, 5 ml",
        price: 17.5,
        isFavorite: false,
        isBasket: false,
      },
      {
        id: 19,
        image: Mascara1,
        title: "Make Up Glam Doll Lash Mascara Make Up, 10 g",
        price: 18.5,
        isFavorite: false,
        isBasket: false,
      },
      {
        id: 20,
        image: Powder2,
        title: "Make Up Compact Powder color 02, 10г",
        price: 19.5,
        isFavorite: false,
        isBasket: false,
      },
    ],
  },
];
